 pipeline {
    agent any

    environment {
        REPO_URL = 'https://github.com/Sijo-K/my-web-app.git'
        STAGING_SERVER = 'Sijo-K@staging-server-address'
        APP_DIR = '/path/to/deployment/dir'
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out code from GitHub...'
                // Cloning the GitHub repository
                git url: env.REPO_URL, branch: 'main'
            }
        }

        stage('Build') {
            steps {
                echo 'Building the application...'
                // Installing dependencies
                sh 'npm install'
            }
        }

        stage('Test') {
            steps {
                echo 'Running tests...'
                // Running tests
                sh 'npm test'
            }
        }

        stage('Deploy to Staging') {
            when {
                expression { return params.DEPLOY_TO_STAGING == true }
            }
            steps {
                echo 'Deploying to the staging server...'
                // Copy files to the staging server using scp
                sh """
                scp -r * ${env.STAGING_SERVER}:${env.APP_DIR}
                """
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
}
